### ISSUE TITLE
Public Testing Pre-Release (1.3.0) Guide

### ISSUE THREAD

**Issue by aletheiadata** [Aletheia-Data/app.aletheiadata.org#64]
### Testing Script

Go to [docs.aletheiadata.org](https://docs.aletheiadata.org/) (read closely). This docs must:

- make sense from a developer PoV 
- have correct information
- have all the information a developer needs to be able to interact with our system

Now, in another tab open [development.aletheiadata.org](https://development.app.aletheiadata.org/). In General, UI test must be done for the following component/features:

- Connection (connect/disconnet)
- Search
- Navigation
- Performance
- UI / UX
- Test on different browsers

Report Channels: 

[#public-testing](https://discord.gg/hYGS26S5gk)

Website: [development.aletheiadata.org](https://development.app.aletheiadata.org/)

### All these feature must work:

- [ ] Login / Logout (Metamask / Magic Link)
- [ ] Search Files
- [ ] Upload File (at least 10 assets):
  - 3 PDF
  - 3 CSV
  - 3 XLS
  - 1 other
- [ ] Save contributor's wallet
- [ ] Navigation without latency or bugs
- [ ] Access to IPFS / Filecoin information
 
**Actions on file:**

- [ ] Download
- [ ] Open "MiniSearch" on CSV
- [ ] Open "Online Excel" on Excel
- [ ] Open PDF on browser
- [ ] Access to CID via RAPID API on CSV / JSON
- [ ] All must be documented on https://docs.aletheiadata.org

**Actions on Rapid API**

- [ ] All endpoints must work
- [ ] Documentation must be correct
- [ ] Check limitations

**Comment by aletheiadata** [comment]
All these feature must work:

- [ ] Login / Logout (Metamask / Magic Link)
- [ ] Search Files
- [ ] Upload File
- [ ] Save contributor's wallet
- [ ] Navigation without latency or bugs
- [ ] Access to IPFS / Filecoin information
**Can do these actions on file:**
- [ ] Download
- [ ] Open "MiniSearch" on CSV
- [ ] Open "Online Excel" on Excel
- [ ] Open PDF on browser
- [ ] Access to CID via RAPID API on CSV / JSON
- [ ] Is all documented on https://docs.aletheiadata.org

**Comment by aletheiadata** [comment]
@Lcdo-Jeremy @natachadelarosa how's testing going? Did you manage to do all the test in the description?

**Comment by Lcdo-Jeremy** [comment]
Hello guys, I'm going to continue with the tests of uploading the PDFs today, since when I was doing it the server crashed
