### ISSUE TITLE
toward 1.3 🏃🏽‍♂️⚡️

### ISSUE THREAD

**Issue by aletheiadata** [Aletheia-Data/app.aletheiadata.org#85]
minor improvements before v1.3.0 public release
test branch: [master](https://app.aletheiadata.org/)

**Home**
- [x] remove arrows icons in homepage
- [x] ~~add percentages to achivements~~ commented for now
- [x] fix counter on widgets (sometimes it stays at 0)
- [x] fix the aletheia image in the right sidebar
- [x] add all icons to categories and show them in homepage
- [x] fix link copywrite at the bottom 
- [x] optimize images
- [x] remove link from imports list

**Listing**
- [x] fix action cta
- [x] increase truncate in link 
- [x] hide upload button

**Single**
- [x] check why some assets are not getting back status
- [x] improve CTA proof
- [x] hide buttons upload
- [x] change `name` in the table for title of the asset (remove asset owner)
- [x] change first column in asset's table #88
- [x] add assetId to all calls to /single/... #87 
- [x] wrong column in sources listing #86

**Comment by aletheiadata** [comment]
@natachadelarosa @Lcdo-Jeremy we're using this issue to track all findings during these tests days. Please if you fund something, posted here and we'll add it to the list.
